### ISSUE TITLE
hxp.Script command and arguments incorrect on haxe 4.0.0-preview.5

### ISSUE THREAD

**Issue by Aidan63** [openfl/hxp#4]
Hello,
In Haxe 4 preview 5 the built in script no longer works correctly when it comes to parsing the command and arguments. Running `haxelib run hxp myArg myOtherArg` on the example script in the readme gets you the following output for `command` and `commandArgs`.

```
Test.hx:8: /tmp/temp_14572014
Test.hx:9: [/media/aidan/archive/programming/haxe/flurry/tools/build,Test,Test,hxp.Script,/home/aidan/haxelib/hxp/git/src,myArg,myOtherArg,Test,/media/aidan/archive/programming/haxe/flurry/tools/build/,myArg,myOtherArg]
```

I'm guessing its to do with this issue which was fixed in preview 5 (https://github.com/HaxeFoundation/haxe/issues/7185) as reverting to preview 4 causes everything to work as expected.

**Comment by jgranick** [comment]
Thanks for the report! I think we have it resolved now, could you give the latest dev a try?

**Comment by jgranick** [comment]
Released on haxelib :smile:
