### ISSUE TITLE
Error: : unknown option '--'.

### ISSUE THREAD

**Issue by zagortenej** [openfl/hxp#8]
This error appears when running with Haxe 4.0.0-rc2 (tested on Linux and OSX). It doesn't matter what the script contains, as long as there's one for hxp to find and try to execute.

To reproduce:

Create file `script.hx` with content:

    class Script {}

Make sure you have haxe 4.0.0.-rc2 in your path:

    $ haxe --version
    4.0.0-rc.2

Run hxp (via alias or via haxelib, same thing) with or without script name parameter:

    $ haxelib run hxp
    Error: : unknown option '--'.

**Comment by zagortenej** [comment]
Btw, hxp works ok with haxe 4.0.0-previe5 :wink:

**Comment by Gama11** [comment]
Sounds like you need this change? https://github.com/openfl/hxp/commit/cfdd869a143d43e504158c5c9a8e540840c463e2

**Comment by jgranick** [comment]
I think this change was released -- can you try `haxelib update`? Thanks :smile:

**Comment by zagortenej** [comment]
Oops I forgot to mention version of hxp I'm using:

    $ haxelib list hxp
    hxp: [1.1.0]

I guess this is the latest? Update gives me:

    $ haxelib update hxp
    hxp is up to date

**Comment by jgranick** [comment]
Thanks

The fix was not released yet.

Could you try `haxelib update hxp` one more time?

**Comment by zagortenej** [comment]
Sure, I've got 1.1.2 now:

    $ haxelib list hxp
    hxp: 1.1.0 [1.1.2]

I guess some libs require 1.1.0, so that one's still there. Nevertheless, the error is gone and my scripts work again. Yay! :smiley: 

Thanks!

**Comment by Gama11** [comment]
>I guess some libs require 1.1.0, so that one's still there.

Haxelib simply doesn't remove old versions on its own. The version in `[]` is the active one.
